# Generated by Django 4.0.1 on 2022-02-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Booking_rooms',
            new_name='Booking_room',
        ),
        migrations.RenameModel(
            old_name='Bulk_discounts',
            new_name='Bulk_discount',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='Seasonal_discounts',
            new_name='Seasonal_discount',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
