# Generated by Django 4.0.1 on 2022-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0002_rename_actions_action_rename_bookings_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='cot',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='disabled_access',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
