# Generated by Django 4.0.1 on 2022-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0003_alter_booking_adults_alter_booking_booked_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cot',
        ),
        migrations.RemoveField(
            model_name='room',
            name='disabled_access',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_price',
        ),
        migrations.AlterField(
            model_name='room_type',
            name='room_type_desc',
            field=models.IntegerField(choices=[(1, 'Luxury Lodge Room'), (2, 'Standard Double'), (3, 'Single'), (4, 'Family Room')]),
        ),
    ]
