# Generated by Django 4.0.1 on 2022-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0004_remove_room_cot_remove_room_disabled_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkin_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
