# Generated by Django 4.0.1 on 2022-02-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0006_alter_booking_first_date_alter_booking_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_type',
            name='room_type_desc',
            field=models.CharField(choices=[('LX', 'Luxury Lodge Room'), ('DB', 'Standard Double'), ('SG', 'Single'), ('FM', 'Family Room')], max_length=40),
        ),
    ]
