# Generated by Django 4.0.1 on 2022-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0007_alter_room_type_room_type_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
