# Generated by Django 4.0.1 on 2022-02-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0008_alter_booking_first_date_alter_booking_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Lodge.customer'),
        ),
    ]
