# Generated by Django 4.0.1 on 2022-02-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0009_checkin_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='customer_id',
        ),
    ]
