# Generated by Django 4.0.1 on 2022-02-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0010_remove_checkin_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Lodge.customer'),
        ),
    ]
