# Generated by Django 4.0.1 on 2022-02-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0012_checked_in_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checked_in_guests',
            new_name='Checked_in_guest',
        ),
    ]
